### ISSUE TITLE
Redo design

### ISSUE THREAD

**Issue by nehero** [nehero/expense-tracker#5]
The design I did was quick and sloppy. It needs to be redone to be responsive instead of showing/hiding different layouts based on what screen size is viewing. Not sure if I want to use a css framework or roll it by hand.

**Comment by se1exin** [comment]
I recommend Pure CSS - its a good lean grid system/framework without the bloat of the likes of Bootstrap

**Comment by se1exin** [comment]
Hey I have had a go at a slightly different layout and colour scheme - not sure if you'll like it or not but do what you want with it

Branch: https://github.com/se1exin/expense-tracker/tree/alternate-design
Demo: http://jcode.pro/expense-tracker/
